# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaffleChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaffleChat
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'SDWebImage'
  pod 'JGProgressHUD'

end
